function [DBTrain_one, DBTest_one] = getFeatures( datasetsname, featsPath, training_split, split, ...
    descriptor, graylevel, prepro, trainSplit, computeCNNFeaturesTrained, sp )

    if strcmp( datasetsname, 'CNMC' )
        DBTest_one = load( fullfile( featsPath, ...
            strcat( datasetsname, '___', ...
            split{2}, '___',...
            descriptor, '___',...
            num2str( graylevel ), '___',...
            prepro{pp}, '.mat') ) );
        DBTest_one = DBTest_one.features;
    else
        DBTest_one  = [];
    end
    
    if( contains( descriptor, 'FT' ) && computeCNNFeaturesTrained == 1 ) % fine-tuned models features
        DBTrain_one = load( fullfile( featsPath, ...
            strcat( datasetsname, '___', ...
            training_split, '___',...
            split{sp} , '___',...
            descriptor, '___',...
            num2str(graylevel), '___',...
            prepro, '.mat') ) );
    elseif( contains( descriptor, 'FT' ) == 0 || computeCNNFeaturesTrained == 0) % standard models features or HC features
        DBTrain_one = load( fullfile( featsPath, ...
            strcat( datasetsname, '___', ...
            split{trainSplit}, '___',...
            descriptor, '___',...
            num2str(graylevel), '___',...
            prepro, '.mat') ) );
    end    
    DBTrain_one = DBTrain_one.features;
end