function [DBTrain, DBTest] = getFeatures( datasetsname, featsPath, training_split, split, ...
    descriptor, graylevel, prepro, trainSplit, computeCNNFeaturesTrained, sp )

    DBTrain = [];
    DBTest  = [];
    if strcmp( datasetsname, 'CNMC' )
        DBTest_one = load( fullfile( featsPath, ...
            strcat( datasetsname, '___', ...
            split{2}, '___',...
            descriptor, '___',...
            num2str( graylevel ), '___',...
            prepro{pp}, '.mat') ) );
        DBTest = [DBTest DBTest_one.features];
    end
    
    if( contains( descriptor, 'FT' ) && computeCNNFeaturesTrained == 1 ) % fine-tuned models features
        DBTrain_one = load( fullfile( featsPath, ...
            strcat( datasetsname, '___', ...
            training_split, '___',...
            split{sp} , '___',...
            descriptor, '___',...
            num2str(graylevel), '___',...
            prepro, '.mat') ) );
    elseif( contains( descriptor, 'FT' ) == 0 || computeCNNFeaturesTrained == 0) % standard models features or HC features
        DBTrain_one = load( fullfile( featsPath, ...
            strcat( datasetsname, '___', ...
            split{trainSplit}, '___',...
            descriptor, '___',...
            num2str(graylevel), '___',...
            prepro, '.mat') ) );
    end
    
    DBTrain = [DBTrain DBTrain_one.features];
    
end